"""
Core newsletter draft generation logic.
"""

import sys
from datetime import datetime, timezone

import anthropic

from .fetcher import fetch_rss_feed, fetch_url_content
from .prompts import SYSTEM_PROMPT, build_user_prompt

RSS_FEED_URL = "https://amiamarketer.substack.com/feed"
MODEL = "claude-opus-4-6"


def generate_newsletter_draft(
    notes: str = "",
    urls: list[str] | None = None,
    rss_url: str = RSS_FEED_URL,
    verbose: bool = True,
) -> str:
    """
    Fetch context, build prompt, call Claude, return the draft as a string.
    """
    urls = urls or []

    # ── 1. Fetch past issues for context ──────────────────────────────────
    if verbose:
        print("  Fetching past issues from RSS feed...", file=sys.stderr)
    try:
        past_issues = fetch_rss_feed(rss_url, max_items=6)
        if verbose:
            print(f"  Got {len(past_issues)} past issues.", file=sys.stderr)
    except Exception as exc:
        print(f"  Warning: could not fetch RSS feed: {exc}", file=sys.stderr)
        past_issues = []

    # ── 2. Fetch any saved URLs ────────────────────────────────────────────
    url_contents = []
    if urls:
        if verbose:
            print(f"  Fetching {len(urls)} saved URL(s)...", file=sys.stderr)
        for url in urls:
            content = fetch_url_content(url)
            url_contents.append({"url": url, "content": content})

    # ── 3. Build prompt ────────────────────────────────────────────────────
    week_of = datetime.now(timezone.utc).strftime("%B %d, %Y")
    user_prompt = build_user_prompt(
        past_issues=past_issues,
        notes=notes,
        url_contents=url_contents,
        week_of=week_of,
    )

    # ── 4. Call Claude ─────────────────────────────────────────────────────
    if verbose:
        print("  Generating draft outline with Claude...", file=sys.stderr)

    client = anthropic.Anthropic()

    full_response = []
    with client.messages.stream(
        model=MODEL,
        max_tokens=4096,
        thinking={"type": "adaptive"},
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": user_prompt}],
    ) as stream:
        for text in stream.text_stream:
            full_response.append(text)
            if verbose:
                print(text, end="", flush=True)

    if verbose:
        print("\n", file=sys.stderr)

    return "".join(full_response)


def save_draft(draft: str, output_dir: str = "drafts") -> str:
    """
    Save the draft to a timestamped markdown file.
    Returns the file path.
    """
    import os

    os.makedirs(output_dir, exist_ok=True)
    date_slug = datetime.now().strftime("%Y-%m-%d")
    filename = f"{date_slug}-newsletter-draft.md"
    filepath = os.path.join(output_dir, filename)

    # Add a header
    header = f"# Newsletter Draft — {datetime.now().strftime('%B %d, %Y')}\n\n"
    header += "_Generated by newsletter-draft-agent. Edit freely — this is a starting point, not a finished piece._\n\n---\n\n"

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(header + draft)

    return filepath
